### ISSUE TITLE
Flaky first time disk selection

### ISSUE THREAD

**Issue by RalphEgas** [MEGA65/mega65-freezemenu#8] opened 2020-04-27 00:37 UTC
When opening freeze menu (after reset) and opening disk selection through either 0 or 1, the list shown only contains 'no disk' and 'internal 3.5"' or '1565 drive 1', not the d81 images. Pressing RUN/STOP to back out and entering the menu again solves this from thereon.

**Comment by gardners** [comment] 2020-04-27 02:32
This is a duplicate of https://github.com/MEGA65/mega65-core/issues/159 and the problem is in HYPPO, not in the Freeze Menu (anything that asks the hypervisor for a directory listing suffers the same problem). So will be fixed there instead of here.

**Closed as completed by gardners** 2020-04-27 02:32 UTC
